---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: devtron-operator
  namespace: devtroncd
spec:
  interval: 5m
  chart:
    spec:
      chart: devtron-operator
      version: 0.22.48
      sourceRef:
        kind: HelmRepository
        name: devtroncd
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
