---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - smtp-relay-secret.sops.yaml
namespace: selfhosted
configMapGenerator:
  - name: smtp-relay
    files:
      - config/maddy.conf
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
