---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - smtp-relay.sops.yaml
namespace: mail
configMapGenerator:
  - name: smtp-relay
    files:
      - maddy/maddy.conf
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
