---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core-cert-manager-base
  namespace: flux-system
spec:
  interval: 5m
  path: "./k8s/manifests/core/cert-manager/cert-manager/base"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core-cert-manager-config
  namespace: flux-system
spec:
  interval: 5m
  path: "./k8s/manifests/core/cert-manager/cert-manager/config"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
