---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core-minio
  namespace: flux-system
spec:
  interval: 5m
  path: "./k8s/manifests/core/minio"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  decryption:
    provider: sops
    secretRef:
      name: sops-age
