---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core-velero
  namespace: flux-system
spec:
  interval: 5m
  path: "./k8s/manifests/core/velero"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
