---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: vaultwarden
      version: 0.1.4
      sourceRef:
        kind: HelmRepository
        name: captnbp
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  values:
    persistence:
      data:
        size: 5Gi
    postgresql:
      size: 5Gi
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: ${CLUSTER_CERT}
      hosts:
        - host: &host "kubeapps.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
          tls:
            - hosts:
                - *host
              secretName: &tls tls.kubeapps
