apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - bitnami.yaml
  - podinfo.yaml
  - banzaicloud.yaml
  - k8-at-home.yaml
  - appuio.yaml
  - external-secrets.yaml
