---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 5m
  chart:
    spec:
      chart: minio
      version: v11.7.19
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    createNamespace: true
    remediation: # perform remediation when helm install fails
      retries: 5
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 5
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  values:
    auth:
      rootPassword: "xg9sHLDf1O"
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hostname: &host "minio.${SECRET_DOMAIN}"
      annotations:
        # cert-manager.io/cluster-issuer: ${CLUSTER_CERT}
        hajimari.io/enable: "true"
        hajimari.io/appName: minio
        hajimari.io/icon: lan
      tls: true
    apiIngress:
      enabled: true
      ingressClassName: "nginx"
      hostname: &host "minio-api.${SECRET_DOMAIN}"
      # annotations:
      # cert-manager.io/cluster-issuer: ${CLUSTER_CERT}
      tls: true
  #AWS_CERT: your base64 encoded custom CA certificate goes here
