apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: minio
spec:
  rules:
    - https:
        paths:
          - backend:
              service:
                name: minio
                port:
                  name: 9000
