apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
spec:
  releaseName: vault-operator
  chart:
    spec:
      chart: vault-operator
      sourceRef:
        kind: HelmRepository
        name: banzaicloud-stable
        namespace: flux-system
      version: "1.15.8"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
