apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-secrets-webhook
spec:
  releaseName: vault-secrets-webhook
  chart:
    spec:
      chart: vault-secrets-webhook
      sourceRef:
        kind: HelmRepository
        name: banzaicloud-stable
        namespace: flux-system
      version: "1.15.11"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
