apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: YWRtaW4=
  AWS_SECRET_ACCESS_KEY: eGc5c0hMRGYxTw==
  AWS_ENDPOINTS: bWluaW8tYXBpLjE5Mi4xNjguMS41MC5uaXAuaW8=
