apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: longhorn-system
type: Opaque
data:
  # AWS_ACCESS_KEY_ID: YWRtaW4=
  # AWS_SECRET_ACCESS_KEY: eGc5c0hMRGYxTw==
  # AWS_ENDPOINTS: bWluaW8tYXBpLjE5Mi4xNjguMS41MC5uaXAuaW8=
  # AWS_ENDPOINTS: aHR0cDovL21pbmlvLWFwaS4xOTIuMTY4LjEuNTAubmlwLmlv
  AWS_ACCESS_KEY_ID: MDYwNEFDRjk3OTNFODEyQTRERjI=
  AWS_SECRET_ACCESS_KEY: IHlCNXN5dkdva1BFU29DcTM1bjhYMXBLOVN0eTVRdEVOUTVKTnI0RTg=
  AWS_ENDPOINTS: aHR0cHM6Ly9zMy5maWxlYmFzZS5jb20=
