---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-v1
  namespace: mediabox
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 15Gi

  #  storageClassName: ceph-block
  storageClassName: longhorn
