---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: mediabox
spec:
  interval: 5m
  chart:
    spec:
      chart: radarr
      version: 16.2.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  values:
    image:
      repository: ghcr.io/k8s-at-home/radarr
      tag: v4.1.0.6175

    env:
      TZ: ${TZ}
    podAnnotations:
      backup.velero.io/backup-volumes: config
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: ${CLUSTER_CERT}
          # nginx.ingress.kubernetes.io/configuration-snippet: |
          #   proxy_set_header Accept-Encoding "";
          #   sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.192.168.1.50.nip.io/css/base/radarr/plex.css"></head>';
          #   sub_filter_once on;
          # external-dns/is-public: "false"
          hajimari.io/enable: "true"
          hajimari.io/appName: radarr
          hajimari.io/icon: "filmstrip"
        hosts:
          - host: &host "radarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
            tls:
              - hosts:
                  - *host
                secretName: &tls tls.radarr

      api:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: ${CLUSTER_CERT}
          # external-dns/is-public: "true"
          # external-dns.alpha.kubernetes.io/target: ipv4.${SECRET_DOMAIN}
          # external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        hosts:
          - host: *host
            paths:
              - path: /api
                pathType: Prefix
            tls:
              - hosts:
                  - *host
                secretName: *tls

    persistence:
      config:
        enabled: true
        existingClaim: radarr-config-v1

      # nfs-nas-media:
      #   enabled: true
      #   type: custom
      #   volumeSpec:
      #     nfs:
      #       server: ${NAS_ADDRESS_2}
      #       path: /tank/
      #   mountPath: /media
      #   readOnly: false

      # nfs-nas-backup:
      #   enabled: true
      #   type: custom
      #   volumeSpec:
      #     nfs:
      #       server: ${NAS_ADDRESS_2}
      #       path: /tank/backup/kubernetes/apps/radarr
      #   mountPath: /config/Backups
      #   readOnly: false

    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups:
        - 5600

    resources:
      requests:
        cpu: 10m
        memory: 512M
      limits:
        memory: 974M

    # prometheus:
    #   podMonitor:
    #     enabled: true
    #     interval: 3m
    #     scrapeTimeout: 1m30s

    # metrics:
    #   enabled: true
    #   serviceMonitor:
    #     interval: 3m
    #     scrapeTimeout: 1m
    #   prometheusRule:
    #     enabled: true
    #   exporter:
    #     image:
    #       repository: ghcr.io/onedr0p/exportarr
    #       tag: v1.1.0
    #     env:
    #       port: 9794
    #       additionalMetrics: true
    #       unknownQueueItems: false
