---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: vaultwarden
      version: 5.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      # -- image repository
      repository: vaultwarden/server
      # -- image pull policy
      pullPolicy: IfNotPresent
      # -- image tag
      tag: 1.27.0

    strategy:
      type: Recreate

    # -- environment variables. See [image docs](https://github.com/dani-garcia/vaultwarden/blob/main/.env.template) for more details.
    # @default -- See below
    env:
      # -- Config dir
      DATA_FOLDER: "config"
      DOMAIN: https://pw.${SECRET_DOMAIN}
      SIGNUPS_ALLOWED: "true"
      SMTP_FROM_NAME: Vaultwarden
      SMTP_HOST: mail.${SECRET_DOMAIN}
      SMTP_FROM: vaulwarden_admin
      SMTP_PORT: 587
      SMTP_SSL: "true"
      TZ: "Europe/Berlin"
      WEBSOCKET_ADDRESS: 0.0.0.0
    # envFrom:
    #   - secretRef:
    #       name: vaultwarden
    # -- Configures service settings for the chart. Normally this does not need to be modified.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            port: 80
          websocket:
            enabled: true
            port: 3012

    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/appName: "Vault"
          hajimari.io/icon: "mdiLock"
        #  traefik.ingress.kubernetes.io/router.tls.domains.0.main: "vaultwarden.${SECRET_DOMAIN}"
        hosts:
          - host: "pw.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: 3012
              - path: /notifications/hub/negotiate
                pathType: Prefix
        tls:
          - hosts:
              - "pw.${SECRET_DOMAIN}"
            secretName: "pw.${SECRET_DOMAIN}"
      admin:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "pw.${SECRET_DOMAIN}"
            paths:
              - path: /admin
                pathType: Prefix
        tls:
          - hosts:
              - "pw.${SECRET_DOMAIN}"
    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      config:
        enabled: true
        #existingClaim: vaultwarden-v1
