apiVersion: v1
kind: Secret
metadata:
    name: sample-tunnel
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:LO4mfIvluw7x4OlxXUcaarGN83VBU80Wg2Qcm+J6gtLALq5BWxWeRw==,iv:i+7KOwE4J20HJJd8p+3zbVhazCn/Zt7aG8MetM/u+Lg=,tag:t3lRiQAvkK+2jWZ/rhBQvQ==,type:str]
    accountID: ENC[AES256_GCM,data:EdmMa060PUoaY/mS/SeXOmTSW3buoFLLlreKFk3gXJE=,iv:ffpYxAvbEOj81YUtZSeZhI9LIXnbwFazYA2ezhvNhJE=,tag:pVpTWStGqNoobQ2vyWca9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3yhxz3wdwaut5dnfqc25g7u7xd6k53dfc8fcykaj09vru7ldgwsytc5u9
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MEVkS2szSG1PVVkwWHZC
              RG5hWDlSZ3BXY2NwTUgvN1dXUkpOTGVPUGdrClRzM1NudTUvbGo1MXl1SGpqMXBp
              UzlPT0NOemVtall3NlUrbVpLaldSN3MKLS0tIGVOTFBvVjhsOVN0TGhEdWZ3THFW
              dWJQV1orYlQ3WSttaDc0U0wyc2VqQnMKYv5zfsPXqN2v/fzqRB8Sv4fMgMMW2tdh
              3/QbRJKuX3P7Ty2VdrNZZkn6HEWU6uFOATDbqrU/CWyNo4tqkv3fAw==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-19T15:47:47Z"
    mac: ENC[AES256_GCM,data:KexNjaiiSNnUrU7YEdV1CeHRcykjSX/55IApROvLNQKWB8NkHlGPTGXsU0UnTVVMokxKIHV7XkYRC1D178mT+ahjHcOsQrgjLSchtA2HtEN747B3z5B6GJJR9CCa+59Age1aMFJ8a70D9jKtoQv80ZnRspE/zhUZK4B3Jw87nrs=,iv:41GmEu3qMX/MnI/PLyWeNikBCJJ2ksXllN6KRuZjZHk=,tag:blkMMNDd6fkNsmk93r5jfQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
