---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudflared
      version: v0.4.3
      sourceRef:
        kind: HelmRepository
        name: khuedoan-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation: # perform remediation when helm install fails
      retries: 5
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 5
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  values:
    credentials:
      existingSecret: cloudflared-credentials
    config:
      tunnel: homelab
      ingress:
        - hostname: "*.${SECRET_DOMAIN}"
          service: https://ingress-nginx-controller.ingress-nginx
          originRequest:
            noTLSVerify: true
        - service: http_status:404
