---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apply-cluster-namespaces
  namespace: flux-system
spec:
  # dependsOn:
  #   - name: apply-manage-flux
  interval: 10m0s
  path: ./k8s/clusters/staging/flux/namespaces
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
