---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apply-cluster-orchestration-core
  namespace: flux-system
spec:
  dependsOn:
    - name: apply-cluster-config
    - name: apply-cluster-repositories
    - name: apply-cluster-namespaces
    # - name: apply-manage-flux
  interval: 10m0s
  path: ./k8s/clusters/staging/flux/orchestration/core
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apply-cluster-orchestration-user
  namespace: flux-system
spec:
  dependsOn:
    - name: apply-cluster-config
    - name: apply-cluster-repositories
    - name: apply-cluster-namespaces
    # - name: apply-manage-flux
  interval: 10m0s
  path: ./k8s/clusters/staging/flux/orchestration/user
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
