---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apply-cluster-crds
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: apply-cluster-config
    - name: apply-cluster-repositories
  #    - name: apply-manage-flux
  path: ./k8s/clusters/staging/crds/
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
