---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apply-cluster-orchestration-core
  namespace: flux-system
spec:
  dependsOn:
    - name: apply-cluster-config
    - name: apply-cluster-repositories
    - name: apply-cluster-namespaces
    # - name: apply-manage-flux
  interval: 10m0s
  path: ./k8s/clusters/staging/flux/orchestration/core
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  patches:
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
        kind: Kustomization
        metadata:
          name: not-used
          namespace: not-used
        spec:
          decryption:
            provider: sops
            secretRef:
              name: sops-age
          postBuild:
            substitute: {}
            substituteFrom:
              - kind: Secret
                name: cluster-secrets
      target:
        kind: Kustomization
        group: kustomize.toolkit.fluxcd.io
        version: v1beta2
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apply-cluster-orchestration-user
  namespace: flux-system
spec:
  dependsOn:
    - name: apply-cluster-config
    - name: apply-cluster-repositories
    - name: apply-cluster-namespaces
    # - name: apply-manage-flux
  interval: 10m0s
  path: ./k8s/clusters/staging/flux/orchestration/user
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: apply-cluster-config
  patches:
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
        kind: Kustomization
        metadata:
          name: not-used
          namespace: not-used
        spec:
          decryption:
            provider: sops
            secretRef:
              name: sops-age
          postBuild:
            substitute: {}
            substituteFrom:
              - kind: Secret
                name: cluster-secrets
              - kind: ConfigMap
                name: apply-cluster-config
      target:
        kind: Kustomization
        group: kustomize.toolkit.fluxcd.io
        version: v1beta2
