apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: network-system
stringData:
    api-token: ENC[AES256_GCM,data:YEW6gz2wHhwreIwS5JYMHeDHTzyjI6PL1eRbdZb1ApglY7xjQ1I1zg==,iv:wPNS1PwJ8a9w0O/qroqfNSYZy3dIOnBR56Y7uEu0k7g=,tag:YXrUzGUENHx8hB2YNy3y4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3yhxz3wdwaut5dnfqc25g7u7xd6k53dfc8fcykaj09vru7ldgwsytc5u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNXcycVY2MUcrOUgrZXFV
            QlZQQUtlNTYrNUh3Tk10Qmtua082T1hEYzI4CjlGcmRwdklBUjFuS3p6OTFOTGta
            dlNCaEtqQ1Nld0ZlMnB2cVM2Z1NjRmMKLS0tIExBcll0NGczRVRNNCtnNUpDVFA2
            VmdlSU9SOVVSRkV5d2NsNll4NWZyTFkK4me0XndQLAHpnQRDByuQBOYeyTgmxAEV
            ePW6p8B1jSITTN/YUW7i4um/uP0kiOknAyTwnXo5uatKvJctmUSqvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-14T17:55:02Z"
    mac: ENC[AES256_GCM,data:bLW9+xJNMzbWpfBrmAWanqbMl9D8OZpfylHFWdew6RAgFFwCaOOCS1YJVbTaq+6JFTpOLt+7mC9j4E0TcBldIQAyvznBJtf6ODJqDGPPt2rxUgeL7sN7ypaLhy6hV9bSwtoijGi6aSF/N1AyDdG5jmA7VC8/a1DNyoUDIYi4R3A=,iv:1QBaq+Uig0lz9hN114aoRwJV5G8vecrxDV8YFuVG2X8=,tag:LTlRI4oC9D34QaoDrO7eow==,type:str]
    pgp: []
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
