---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: user-mediabox-radarr
  namespace: flux-system
spec:
  interval: 5m
  path: "./k8s/manifests/user/mediabox/radarr"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
