---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubeapps
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: kubeapps
      version: 12.0.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  values:
    authProxy:
      enabled: true
      provider: oidc
      clientID: kubeapps-oauth2-proxy
      clientSecret: "kubeappsClientSecret"
      cookieSecret: "kubeappskubeapps"
      extraFlags:
        - --oidc-issuer-url="https://dex.${SECRET_DOMAIN}"
        # IMPORTANT: We are overwriting the scope option to include the workload clusters' clientids in the audience.
        - --scope=openid email groups
        # TODO: Update to provide the dex ca via --provider-ca-file and mounting etc.
        - --ssl-insecure-skip-verify=true
        # Since Kubeapps is running without TLS, can't use secure cookies
        - --cookie-secure=false
        # If you need to access the actual token in the frontend for testing, uncomment the following.
        # - --set-authorization-header=true
