apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
spec:
  releaseName: minio
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "11.x"
  interval: 0h1m0s
  install:
    remediation:
      retries: 3
  values:
    podAnnotations:
      vault.security.banzaicloud.io/vault-addr: "http://vault.vault:8200"
      vault.security.banzaicloud.io/vault-role: "default"
      vault.security.banzaicloud.io/vault-skip-verify: "false"
      vault.security.banzaicloud.io/vault-agent: "false"
      vault.security.banzaicloud.io/vault-path: "kubernetes"
    auth:
      existingSecret: minio-credentials
