---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 6h
  maxHistory: 2
  timeout: 20m
  chart:
    spec:
      chart: tailscale-relay
      version: 0.1.11
      sourceRef:
        kind: HelmRepository
        name: mvisonneau
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
    remediation: # perform remediation when helm install fails
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation: # perform remediation when helm upgrade fails
      retries: 5
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  values:
    config:
      authKey: "tskey-auth-k2TSGD2CNTRL-WMy3A78prs6dWZF183KTw6fa878dV48Fb"
      variables:
        TAILSCALE_ADVERTISE_ROUTES: "10.96.0.0/12"
