apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale
  namespace: tailscale
  labels:
    app.kubernetes.io/name: tailscale
    app.kubernetes.io/part-of: tailscale
    app.kubernetes.io/version: 1.32.2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tailscale
      app.kubernetes.io/part-of: tailscale
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tailscale
        app.kubernetes.io/part-of: tailscale
        app.kubernetes.io/version: 1.32.2
    spec:
      serviceAccountName: tailscale
      terminationGracePeriodSeconds: 60
      containers:
        - name: tailscale
          image: ghcr.io/tailscale/tailscale:v1.32.2
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: TS_USERSPACE
              value: "false"
            - name: TS_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-subnet-router-secrets
                  key: AUTH_KEY
            - name: TS_DEST_IP
              value: 192.168.1.50 #TODO: cluster ip of nginx ingress
            - name: TS_EXTRA_ARGS
              value: --hostname=nutria
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
