apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: backup-tests
  namespace: k8up
spec:
  keepJobs: 4
  promURL: http://minio.minio:9000
  backend:
    repoPasswordSecretRef:
      name: backup-repo
      key: password
    s3:
      endpoint: http://minio.minio:9000
      bucket: backups
      accessKeyIDSecretRef:
        name: minio-credentials
        key: root-user
      secretAccessKeySecretRef:
        name: minio-credentials
        key: root-password
