apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k8up
resources:
  - namespace.yaml
  - https://github.com/k8up-io/k8up/releases/download/v2.3.2/k8up-crd.yaml
  - release.yaml
  - backup-repo.yaml
  - secrets.yaml
