apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8up
spec:
  releaseName: k8up
  chart:
    spec:
      chart: k8up
      sourceRef:
        kind: HelmRepository
        name: appuio
        namespace: flux-system
      version: "2.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
