apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8up-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: k8up-secrets
  data:
    # Connectors
    - secretKey: MINIO_USER
      remoteRef:
        key: /infra/minio
        property: user
    - secretKey: MINIO_PASSWORD
      remoteRef:
        key: /infra/minio
        property: password
