# ---
# apiVersion: monitoring.coreos.com/v1
# kind: Probe
# metadata:
#   name: hajimari-http
#   namespace: services
# spec:
#   jobName: hajimari-http
#   interval: 1m
#   scrapeTimeout: 5s
#   module: http_2xx
#   prober:
#     url: blackbox-exporter.system-monitoring:9115
#   targets:
#     staticConfig:
#       static:
#         - "https://hajimari.${EXTERNAL_DOMAIN}"
