---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
  namespace: dex
spec:
  interval: 5m
  chart:
    spec:
      chart: dex
      version: 0.12.1
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: flux-system
      interval: 5m
  values:
    config:
      issuer: "https://dex.${SECRET_DOMAIN}"
      enablePasswordDB: true
      storage:
        type: memory
    service:
      annotations:
        cfargotunnel.com/cluster-tunnel: k3s-cluster-tunnel
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: ${CLUSTER_CERT}
      hosts:
        - host: &host "dex.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
          tls:
            - hosts:
                - *host
              secretName: &tls tls.radarr
