---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
  namespace: dex
spec:
  interval: 5m
  chart:
    spec:
      chart: dex
      version: 0.12.1
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: flux-system
      interval: 5m
  values:
    config:
      issuer: "https://dex.${SECRET_DOMAIN}"
      enablePasswordDB: true
      storage:
        type: memory
      oauth2:
        skipApprovalScreen: true
      frontend:
        proxypassAccessTokenAsBearer: true
      staticClients:
        - id: kubeapps-oauth2-proxy
          redirectURIs:
            - "https://kubeapps.${SECRET_DOMAIN}/oauth2/callback"
          name: "Kubeapps on TKG test Login"
          secret: "kubeappsClientSecret"
        - id: grafana-sso
          name: Grafana
          redirectURIs:
            - "https://grafana.${SECRET_DOMAIN}/login/generic_oauth"
          secretEnv: "kubeappsClientSecret"
      staticPasswords:
        - email: "admin@example.com"
          # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
          hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
          username: "admin"
          userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
    service:
      annotations:
        cfargotunnel.com/cluster-tunnel: k3s-cluster-tunnel
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: ${CLUSTER_CERT}
      hosts:
        - host: &host "dex.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
          tls:
            - hosts:
                - *host
              secretName: &tls tls.dex
