apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:79Td0H51UaLcnOAy3kxU/nGJCGiwAtbO5A==,iv:77GZfdzkDFj3bR7iU8Usnu4j0fkgeYYgq98BswuBCS8=,tag:YTjwb7dqoFzu06aPq92Qtw==,type:comment]
    SECRET_DOMAIN: ENC[AES256_GCM,data:dzlDa2JxhBF2DkzvaAqw2RXxqVI6XaIeEd2F,iv:lSrO76zic1P9YFnyEpD11n9i8vzLPXWMwwFJYkbo+q4=,tag:CypGbuR6W8nLYde4l4Km6Q==,type:str]
    EMAIL_1: ENC[AES256_GCM,data:ZT99mDtCZd23nkn26Yar61tnc6qAsg==,iv:A3656B6QquhSKYTvaL7Pgnvr3TUoXZrpyDaEOsBtvn0=,tag:lrDGTb7sHduZXZdvLEl9qg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3yhxz3wdwaut5dnfqc25g7u7xd6k53dfc8fcykaj09vru7ldgwsytc5u9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZEovMklRUEVJQ0xvMUgz
            dUNyTjRSRzRsei9GaUQ1WmoxTWYrUXYvM0h3CkpGbjR6SzI0azVpUUpzR2NwenYy
            aURLMmtSMElNWHdSaVNTdTNSRjN1ZWsKLS0tIEFMak5PVnhPQ21nM1dpKysxcTY4
            Z3VRa21VZmZTUkNONUV1TGxja3h6UXcKJhottx1AflCxn5MoEREUmL0ID8mKAJ+1
            Ql3+8z8nTkRBF/dM2d4pSg+ILadiM5jVH0NWWRR/+/1dgRMc5k1jTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-15T03:24:52Z"
    mac: ENC[AES256_GCM,data:znaS3UWkv7n5xrwJA9mEUYfv688oB0+Xu87bLXQmsgtD64mjnPqU4PbAJSR5VrrL1S6A3E9Ns+9FqdackQBcNPQ0twJPRWdNVQiV8MVspZR0ByrctQGkTFBToS36v4K5uQ0uE47ZPocT731apDPSkSFhQsLsnkyKXupCoPuRwBk=,iv:eH5zqaWQ25kweaVpWqDBMn84+sS+BEn7FcmrQyqb9yY=,tag:Mrq5pfuNVajGz0U6p3Y3vg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
