---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: home-cluster
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/imerkle/flux2-kustomize-helm-example
  ignore: |
    # exclude all
    /*
    # include gitops dirs
    !/k8s/global
    !/k8s/clusters/staging
    !/k8s/manifests
    # exclude files from gitops dirs
    /k8s/**/*.md
    /k8s/**/*.tmpl
